import type { HisPatientHistory } from '@/services/his/types';
import type { AppPatient } from '@/types/appState';
import {
  buildPatientContext,
  getPatientContextId,
  getPatientContextName,
} from '@/utils/patientContext';

function readPatientFieldText(
  source: Record<string, unknown> | null | undefined,
  keys: string[],
): string {
  if (!source) {
    return '';
  }

  for (const key of keys) {
    const value = source[key];
    if (typeof value === 'string' && value.trim() !== '') {
      return value.trim();
    }
    if (typeof value === 'number' && Number.isFinite(value)) {
      return String(value);
    }
  }

  return '';
}

function uniqHistoryTexts(values: Array<string | null | undefined>): string[] {
  return Array.from(new Set(
    values
      .map((value) => (typeof value === 'string' ? value.trim() : ''))
      .filter(Boolean),
  ));
}

function isAutoGeneratedPastHistoryPlaceholder(value: string): boolean {
  const normalized = value.replace(/\s+/g, '');
  return normalized === '未提供既往病史。'
    || normalized === '未提供既往史。'
    || normalized === '未见明确既往史记录。';
}

function buildPastMedicalHistorySummary(
  patient: AppPatient | null,
  hisHistory: HisPatientHistory | null,
): string {
  const directHistory = readPatientFieldText(patient as Record<string, unknown>, [
    'pastMedicalHistory',
    'past_medical_history',
    'pastMedicalHistoryText',
  ]);
  if (
    directHistory
    && !isAutoGeneratedPastHistoryPlaceholder(directHistory)
    && !directHistory.startsWith('既往门诊记录：')
  ) {
    return directHistory;
  }

  return uniqHistoryTexts(hisHistory?.pastMedicalHistory || []).join('；');
}

function buildAllergyHistorySummary(
  patient: AppPatient | null,
  hisHistory: HisPatientHistory | null,
): string {
  const directHistory = readPatientFieldText(patient as Record<string, unknown>, [
    'allergyHistory',
    'allergy_history',
    'allergyHistoryText',
  ]);
  return directHistory || uniqHistoryTexts(hisHistory?.allergyHistory || []).join('；');
}

export function applyReceptionClinicalHistorySummaries(
  patient: AppPatient | null,
  hisHistory: HisPatientHistory | null,
): AppPatient | null {
  if (!patient) {
    return patient;
  }

  const pastMedicalHistory = buildPastMedicalHistorySummary(patient, hisHistory);
  const allergyHistory = buildAllergyHistorySummary(patient, hisHistory);

  return {
    ...patient,
    clinical: {
      ...patient.clinical,
      pastMedicalHistory: pastMedicalHistory || undefined,
      allergyHistory: allergyHistory || undefined,
      hisHistory,
    },
    hisHistory,
    patientHistory: hisHistory,
    pastMedicalHistory: pastMedicalHistory || undefined,
    allergyHistory: allergyHistory || undefined,
  };
}

export function buildReceptionPatientDraft(
  payload: Record<string, unknown> | null | undefined,
): AppPatient | null {
  return buildPatientContext({ payload });
}

export function resolveIncomingPatientTracking(
  payload: Record<string, unknown> | null | undefined,
): {
  patientId?: string;
  patientName?: string;
} {
  const incomingPatient = buildReceptionPatientDraft(payload);
  return {
    patientId: getPatientContextId(incomingPatient) || undefined,
    patientName: getPatientContextName(incomingPatient) || undefined,
  };
}
