###
POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### AI住院信息上下文获取
POST http://192.168.201.140:5680/rbmh-phis/api/phis.aiInpatientEmrContextService/buildContext
Content-Type: application/json
cookie: tk=66c59a8aea39de0001b56d61

[{"idAdsn":"6a33538aa5e923243665cf0a"}]


### 根据就诊记录获取病历列表
POST http://192.168.201.140:5680/rbmh-phis/api/otms.rpcEmrEditorLookService/getLookMedList
Content-Type: application/json
cookie: tk=66c59a8aea39de0001b56d61

[{"idApp": "42","idTet":"xswjj","idHospital":"6a2d5b06a5e9237869002f7d"}]

### 根据病历信息获取病历内容
POST http://192.168.201.140:5680/rbmh-phis/api/otms.rpcEmrEditorLookService/getMedContentLook
Content-Type: application/json
cookie: tk=66c59a8aea39de0001b56d61

[{"idApp": "42","idTet":"xswjj","idMedrecdoc":"6a2d5b3aa5e923322e5528bb", "courseShow": 0}]


### AI门诊信息上下文获取
POST http://192.168.201.140:5680/rbmh-phis/api/phis.aiInpatientEmrContextService/buildOutpatientFollowUpContext
Content-Type: application/json
cookie: tk=6a38f7abc1946b430432fa55

[{"idPi":"660851762d699a12a8e7e697","idVis":"6a3ddb5fa5e9234cf95ff24e"}]



### 检验开单项目查询
POST http://192.168.201.140:5680/rbmh-phis/api/phis.hiCliLisCategorySubService/queryItemListByIdLisCategory
Content-Type: application/json
cookie: tk=6a38f7abc1946b430432fa55

[{"start":0,"limit":10,"sort":null,"cnd":[],"cndData":{},"params":{"instr":"_"}}]


### AI报告信息上下文获取(测试环境)
POST http://192.168.201.140:5680/rbmh-phis/api/phis.aiInpatientEmrContextService/buildOutpatientFollowUpReportResults
Content-Type: application/json
cookie: tk=6a38f7abc1946b430432fa55

[{"idVis":"6a4200b6a5e92373835abdc7","idPi":"675e4d60402c9700010fc11b"}]

### AI报告信息上下文获取(正式环境)
POST http://192.168.204.13:30010/phis/api/phis.aiInpatientEmrContextService/buildOutpatientFollowUpReportResults
Content-Type: application/json
cookie: tk=6a4450eddb972f0001dbc52f

[{"idVis":"6a4af922eb95720001f8276a","idPi":"66084e8c2d699a12a8b71f69"}]

### 查询可开具的检查检验项目
POST http://192.168.201.140:5680/rbmh-phis/api/phis.aiInpatientEmrContextService/queryAvailableExamLabItems
Content-Type: application/json
cookie: tk=6a4b4b32a5e9235103c3f464

[{}]

### 查询可用库存药品
POST http://192.168.201.140:5680/rbmh-phis/api/phis.medicineDrpQueryService/queryInvSubList
Content-Type: application/json
cookie: tk=6a169dcba5e9236070cfff5d

[
  {
    "limit": -1,
    "params": {
      "amountType": "1",
      "fgActiveType": "1",
      "idSto": "1760",
      "naMedPro": null,
      "sdBasMed": null,
      "sdMed": null,
      "sdMedType": null
    },
    "sort": null,
    "start": 0
  }
]
