/**
 * App 级接诊状态机 controller。
 *
 * 负责 HIS 患者补全、接诊并发保护、风险胶囊状态和患者切换清理。
 * Tauri 事件注册、SDK handshake、具体问诊 / 语音结果页导航仍留在调用方。
 *
 * @module app/events/useReceptionController
 */

import type { Ref } from 'vue';
import { getWindowSizeForView, type ViewType } from '@/constants/windowSizes';
import { analyzePatientRisks } from '@/services/llm';
import { trackApiCall, trackError } from '@/services/operationTracker';
import { getHisAdapter } from '@/services/his';
import type { HisPatientHistory } from '@/services/his/types';
import type { AppPatient } from '@/types/appState';
import {
  buildPatientContext,
  getPatientContextAgeText,
  getPatientContextAnchorId,
  getPatientContextGenderCode,
  getPatientContextGenderText,
  getPatientContextHistory,
  getPatientContextId,
  getPatientContextName,
} from '@/utils/patientContext';
import type { RiskItem } from '@features/reception-risk';

export interface PatientRisksPayload {
  idPi?: string;
  idVis?: string;
  patientId?: string;
  visitId?: string;
  naPi?: string;
  name?: string;
  sdSexText?: string;
  gender?: string;
  ageText?: string;
  age?: string;
  chiefComplaint?: string;
  historyOfPresentIllness?: string;
  pastMedicalHistory?: string;
  diagnosis?: string;
  allergyHistory?: string;
  risks?: RiskItem[];
  [key: string]: unknown;
}

export interface StartConsultationPayload {
  idPi?: string;
  idVis?: string;
  patientId?: string;
  visitId?: string;
  naPi?: string;
  name?: string;
  ageText?: string;
  sdSexText?: string;
  [key: string]: unknown;
}

export interface SessionAssistPayload extends StartConsultationPayload {
  action?: string;
  historyOfPresentIllness?: string;
  pastMedicalHistory?: string;
  diagnosis?: string;
  vitals?: string;
  allergyHistory?: string;
}

export interface ReceptionControllerOptions {
  currentView: Ref<ViewType>;
  isWorking: Ref<boolean>;
  currentPatient: Ref<AppPatient | null>;
  riskState: {
    riskPatientName: Ref<string>;
    riskPatientGender: Ref<'M' | 'F'>;
    riskPatientAge: Ref<number>;
    riskItems: Ref<RiskItem[]>;
    isRiskAnalyzing: Ref<boolean>;
  };
  showToast: (msg: string, type?: 'success' | 'error' | 'info', duration?: number) => void;
  workMode: {
    enterWorkMode: (customW?: number, customH?: number) => Promise<void>;
  };
  resetVoiceSessionState: () => void;
  clearVoiceConsultationCache: (patient?: AppPatient | null) => void;
  clearMinimizedConsultationSessions: () => void;
}

function readPatientFieldText(
  source: Record<string, unknown> | null | undefined,
  keys: string[]
): string {
  if (!source) {
    return '';
  }

  for (const key of keys) {
    const value = source[key];
    if (typeof value === 'string' && value.trim() !== '') {
      return value.trim();
    }
    if (typeof value === 'number' && Number.isFinite(value)) {
      return String(value);
    }
  }

  return '';
}

function uniqHistoryTexts(values: Array<string | null | undefined>): string[] {
  return Array.from(new Set(
    values
      .map((value) => (typeof value === 'string' ? value.trim() : ''))
      .filter(Boolean)
  ));
}

function isAutoGeneratedPastHistoryPlaceholder(value: string): boolean {
  const normalized = value.replace(/\s+/g, '');
  return normalized === '未提供既往病史。'
    || normalized === '未提供既往史。'
    || normalized === '未见明确既往史记录。';
}

function isVisitHistorySummary(value: string): boolean {
  return value.startsWith('既往门诊记录：');
}

function buildPastMedicalHistorySummary(
  patient: AppPatient | null,
  hisHistory: HisPatientHistory | null
): string {
  const directHistory = readPatientFieldText(patient as Record<string, unknown>, [
    'pastMedicalHistory',
    'past_medical_history',
    'pastMedicalHistoryText',
  ]);
  if (directHistory && !isAutoGeneratedPastHistoryPlaceholder(directHistory) && !isVisitHistorySummary(directHistory)) {
    return directHistory;
  }

  const structuredHistory = uniqHistoryTexts(hisHistory?.pastMedicalHistory || []);
  if (structuredHistory.length > 0) {
    return structuredHistory.join('；');
  }

  return '';
}

function buildAllergyHistorySummary(
  patient: AppPatient | null,
  hisHistory: HisPatientHistory | null
): string {
  const directHistory = readPatientFieldText(patient as Record<string, unknown>, [
    'allergyHistory',
    'allergy_history',
    'allergyHistoryText',
  ]);
  if (directHistory) {
    return directHistory;
  }

  return uniqHistoryTexts(hisHistory?.allergyHistory || []).join('；');
}

function applyClinicalHistorySummaries(
  patient: AppPatient | null,
  hisHistory: HisPatientHistory | null,
): AppPatient | null {
  if (!patient) {
    return patient;
  }

  const pastMedicalHistory = buildPastMedicalHistorySummary(patient, hisHistory);
  const allergyHistory = buildAllergyHistorySummary(patient, hisHistory);

  return {
    ...patient,
    clinical: {
      ...patient.clinical,
      pastMedicalHistory: pastMedicalHistory || undefined,
      allergyHistory: allergyHistory || undefined,
      hisHistory,
    },
    hisHistory,
    patientHistory: hisHistory,
    pastMedicalHistory: pastMedicalHistory || undefined,
    allergyHistory: allergyHistory || undefined,
  };
}

function syncRiskStateFromPatient(patient: AppPatient | null): {
  patientName: string;
  patientGender: 'M' | 'F';
  patientAge: number;
} {
  const patientName = getPatientContextName(patient) || '未知患者';
  const genderCode = getPatientContextGenderCode(patient);
  const genderText = getPatientContextGenderText(patient);
  const patientGender: 'M' | 'F' = genderCode === 'F' || genderText.includes('女') ? 'F' : 'M';
  const ageSource = getPatientContextAgeText(patient);
  const patientAge = Number.parseInt(ageSource, 10) || 0;

  return { patientName, patientGender, patientAge };
}

function buildIncomingPatientDraft(
  payload: Record<string, unknown> | null | undefined,
): AppPatient | null {
  return buildPatientContext({ payload });
}

async function hydratePatientContextFromHis(
  currentPatient: AppPatient | null,
  payload: StartConsultationPayload | SessionAssistPayload | PatientRisksPayload | null | undefined,
  source: string,
): Promise<AppPatient | null> {
  const nextDraft = buildPatientContext({
    existing: currentPatient,
    payload: payload as Record<string, unknown> | null | undefined,
    source,
    receptionEnsured: true,
  });
  const patientId = getPatientContextId(nextDraft);
  if (!patientId) {
    return nextDraft;
  }

  const existingHistory = getPatientContextHistory(nextDraft);
  const samePatientLoaded = currentPatient
    && getPatientContextId(currentPatient) === patientId
    && (currentPatient.receptionEnsured || currentPatient._receptionEnsured)
    && existingHistory;
  if (samePatientLoaded) {
    return nextDraft;
  }

  const adapter = getHisAdapter();
  if (!adapter) {
    return nextDraft;
  }

  const hisInfo = await adapter.fetchPatientInfo(patientId);
  const hisHistory = await adapter.fetchPatientHistory(patientId);
  let hydrated = buildPatientContext({
    existing: nextDraft,
    payload: payload as Record<string, unknown> | null | undefined,
    hisInfo,
    hisHistory,
    source,
    receptionEnsured: true,
  });

  hydrated = applyClinicalHistorySummaries(hydrated, hisHistory);

  return hydrated;
}

export function resolveIncomingPatientTracking(
  payload: Record<string, unknown> | null | undefined,
): {
  patientId?: string;
  patientName?: string;
} {
  const incomingPatient = buildIncomingPatientDraft(payload);
  return {
    patientId: getPatientContextId(incomingPatient) || undefined,
    patientName: getPatientContextName(incomingPatient) || undefined,
  };
}

export function useReceptionController(options: ReceptionControllerOptions) {
  const {
    currentView,
    isWorking,
    currentPatient,
    riskState,
    showToast,
    workMode,
    resetVoiceSessionState,
    clearVoiceConsultationCache,
    clearMinimizedConsultationSessions,
  } = options;

  const {
    riskPatientName,
    riskPatientGender,
    riskPatientAge,
    riskItems,
    isRiskAnalyzing,
  } = riskState;

  let activeReceptionPromise: Promise<boolean> | null = null;
  let activeReceptionPatientId: string | null = null;
  let receptionFlowVersion = 0;

  function invalidateReceptionFlow(): void {
    receptionFlowVersion += 1;
    activeReceptionPromise = null;
    activeReceptionPatientId = null;
  }

  function clearVoiceStateWhenPatientSwitches(
    previousPatient: AppPatient | null,
    nextPatient: AppPatient | null
  ): void {
    const previousAnchorId = getPatientContextAnchorId(previousPatient);
    const nextAnchorId = getPatientContextAnchorId(nextPatient);
    if (!previousAnchorId || !nextAnchorId || previousAnchorId === nextAnchorId) {
      return;
    }

    clearVoiceConsultationCache(previousPatient);
    resetVoiceSessionState();
    // 恢复入口要和患者上下文绑定：切换到其他患者后旧患者现场失效。
    clearMinimizedConsultationSessions();
    console.info('[ReceptionController] Cleared voice cache after patient switch', {
      previousAnchorId,
      nextAnchorId,
    });
  }

  async function openReceptionCapsule(): Promise<void> {
    currentView.value = 'reception-capsule';
    const receptionSize = getWindowSizeForView('reception-capsule');
    if (!isWorking.value) {
      await workMode.enterWorkMode(receptionSize.width, receptionSize.height);
    } else {
      workMode.enterWorkMode(receptionSize.width, receptionSize.height);
    }
  }

  async function executeReceptionFlow(payload: StartConsultationPayload, quietMode = false): Promise<boolean> {
    const patientId = getPatientContextId(buildIncomingPatientDraft(payload as Record<string, unknown> | null | undefined));
    if (!patientId) {
      showToast('接诊失败：未提供患者ID', 'error');
      return false;
    }

    if (activeReceptionPromise) {
      if (activeReceptionPatientId === patientId) {
        console.log('[ReceptionController] Waiting for existing reception flow for patient:', patientId);
        return activeReceptionPromise;
      } else {
        showToast('系统正在接诊其他患者，请稍候再试', 'error');
        return false;
      }
    }

    const flowVersion = receptionFlowVersion + 1;
    receptionFlowVersion = flowVersion;
    activeReceptionPatientId = patientId;

    activeReceptionPromise = (async () => {
      trackApiCall('his_receive_patient', true, undefined, { patientId, auto: quietMode });
      try {
        const nextPatient = await hydratePatientContextFromHis(currentPatient.value, payload, quietMode ? 'reception-auto' : 'receive-patient');
        if (flowVersion !== receptionFlowVersion) {
          console.info('[ReceptionController] Ignore stale reception result after flow invalidation:', patientId);
          return false;
        }
        if (!nextPatient) {
          showToast('接诊失败：患者上下文初始化失败', 'error');
          return false;
        }
        clearVoiceStateWhenPatientSwitches(currentPatient.value, nextPatient);
        currentPatient.value = nextPatient;

        await openReceptionCapsule();

        const riskStateSnapshot = syncRiskStateFromPatient(currentPatient.value);
        riskPatientName.value = riskStateSnapshot.patientName;
        riskPatientGender.value = riskStateSnapshot.patientGender;
        riskPatientAge.value = riskStateSnapshot.patientAge;
        riskItems.value = [];
        isRiskAnalyzing.value = true;

        try {
          const risks = await analyzePatientRisks(currentPatient.value);
          if (flowVersion !== receptionFlowVersion) {
            console.info('[ReceptionController] Ignore stale risk analysis result after flow invalidation:', patientId);
            return false;
          }
          console.log('LLM Risk Analysis Result after reception:', risks);
          riskItems.value = risks || [];
        } finally {
          if (flowVersion === receptionFlowVersion) {
            isRiskAnalyzing.value = false;
          }
        }

        return true;
      } catch (e) {
        if (flowVersion !== receptionFlowVersion) {
          console.info('[ReceptionController] Ignore stale reception error after flow invalidation:', patientId, e);
          return false;
        }
        console.error('Patient reception failed:', e);
        trackError('receive_patient_failed', e);
        showToast('接诊处理异常', 'error');
        return false;
      }
    })();

    try {
      return await activeReceptionPromise;
    } finally {
      if (flowVersion === receptionFlowVersion) {
        activeReceptionPromise = null;
        activeReceptionPatientId = null;
      }
    }
  }

  async function ensureReceptionContext(
    payload: StartConsultationPayload | SessionAssistPayload | null | undefined
  ): Promise<boolean> {
    const incomingId = getPatientContextId(buildIncomingPatientDraft(payload as Record<string, unknown> | null | undefined));
    const currentId = getPatientContextId(currentPatient.value);
    const currentReceptionEnsured = Boolean(currentPatient.value?.receptionEnsured || currentPatient.value?._receptionEnsured);

    if (currentPatient.value && currentId && currentReceptionEnsured) {
      if (incomingId && incomingId !== currentId) {
        showToast('当前已接诊其他患者，请先结束当前就诊', 'error');
        return false;
      }
      return true;
    }

    if (!incomingId) {
      showToast('请先接诊患者', 'error');
      return false;
    }

    console.log('[ReceptionController] Auto-triggering patient reception from context check');
    return await executeReceptionFlow(payload as StartConsultationPayload, true);
  }

  function mergeCurrentPatient(
    payload: StartConsultationPayload | SessionAssistPayload | null | undefined,
    overrides?: Partial<AppPatient>,
  ): void {
    currentPatient.value = buildPatientContext({
      existing: currentPatient.value,
      payload: payload as Record<string, unknown> | null | undefined,
      source: currentPatient.value?.source || 'event-payload',
      receptionEnsured: currentPatient.value?.receptionEnsured ?? currentPatient.value?._receptionEnsured,
      overrides,
    });
  }

  async function showPatientRisks(data: PatientRisksPayload): Promise<void> {
    const tracking = resolveIncomingPatientTracking(data as Record<string, unknown> | null | undefined);
    trackApiCall('his_patient_risks', true, undefined, {
      patientId: tracking.patientId,
      patientName: tracking.patientName,
      riskCount: data.risks?.length,
    });

    const nextPatient = await hydratePatientContextFromHis(currentPatient.value, data, 'show-patient-risks');
    clearVoiceStateWhenPatientSwitches(currentPatient.value, nextPatient);
    currentPatient.value = nextPatient;
    const riskStateSnapshot = syncRiskStateFromPatient(currentPatient.value);
    riskPatientName.value = riskStateSnapshot.patientName;
    riskPatientGender.value = riskStateSnapshot.patientGender;
    riskPatientAge.value = riskStateSnapshot.patientAge;
    riskItems.value = [];
    isRiskAnalyzing.value = true;

    currentView.value = 'reception-capsule';
    const receptionSize = getWindowSizeForView('reception-capsule', {
      expanded: !!data.risks?.length,
      riskCount: data.risks?.length ?? 0,
    });
    if (!isWorking.value) {
      await workMode.enterWorkMode(receptionSize.width, receptionSize.height);
    } else {
      workMode.enterWorkMode(receptionSize.width, receptionSize.height);
    }

    if (data.risks && data.risks.length > 0) {
      riskItems.value = data.risks;
      isRiskAnalyzing.value = false;
      return;
    }

    try {
      const risks = await analyzePatientRisks(currentPatient.value);
      console.log('LLM Risk Analysis Result:', risks);
      riskItems.value = risks || [];
    } catch (e) {
      console.error('Risk analysis error:', e);
      trackError('risk_analysis_failed', e);
      showToast('风险评估失败', 'error');
    } finally {
      isRiskAnalyzing.value = false;
    }
  }

  return {
    executeReceptionFlow,
    ensureReceptionContext,
    invalidateReceptionFlow,
    mergeCurrentPatient,
    showPatientRisks,
  };
}
