export const generalConditionConfig = {
  key: 'general',
  name: '一般情况问诊',
  config: {
    sections: [
      {
        id: 'general_section',
        title: '一般情况问诊',
        fields: [
          {
            id: 'spirit',
            key: 'spirit',
            label: '精神',
            type: 'radio',
            props: {
              options: ['精神尚可', '精神疲惫', '精神亢奋', '服药后', '其他'],
              otherOptionLabel: '其他',
              otherDetailKey: 'spiritOtherDetail',
              otherPlaceholder: '请输入精神情况详情',
            },
            storageKey: 'spirit',
          },
          {
            id: 'sleep',
            key: 'sleep',
            label: '睡眠',
            type: 'radio',
            props: {
              options: ['睡眠正常', '睡眠一般', '睡眠欠佳', '睡眠差', '其他'],
              otherOptionLabel: '其他',
              otherDetailKey: 'sleepOtherDetail',
              otherPlaceholder: '请输入睡眠情况详情',
            },
            storageKey: 'sleep',
          },
          {
            id: 'appetite',
            key: 'appetite',
            label: '食欲',
            type: 'radio',
            props: {
              options: ['食欲正常', '食欲增加', '食欲减退', '其他'],
              otherOptionLabel: '其他',
              otherDetailKey: 'appetiteOtherDetail',
              otherPlaceholder: '请输入食欲情况详情',
            },
            storageKey: 'appetite',
          },
          {
            id: 'urination',
            key: 'urination',
            label: '小便',
            type: 'radio',
            props: {
              options: ['小便正常', '小便增多', '小便减少', '其他'],
              otherOptionLabel: '其他',
              otherDetailKey: 'urinationOtherDetail',
              otherPlaceholder: '请输入小便情况详情',
            },
            storageKey: 'urination',
          },
          {
            id: 'stool',
            key: 'stool',
            label: '大便',
            type: 'radio',
            props: {
              options: ['大便正常', '大便增多', '大便减少', '其他'],
              otherOptionLabel: '其他',
              otherDetailKey: 'stoolOtherDetail',
              otherPlaceholder: '请输入大便情况详情',
            },
            storageKey: 'stool',
          },
          {
            id: 'weight',
            key: 'weight',
            label: '体重',
            type: 'radio',
            props: {
              options: ['体重无变化', '体重增加', '体重减轻', '其他'],
              otherOptionLabel: '其他',
              otherDetailKey: 'weightOtherDetail',
              otherPlaceholder: '请输入体重变化详情',
            },
            storageKey: 'weight',
          },
        ],
      },
    ],
  },
};

export const tcmInquiryConfig = {
  key: 'tcm_signs',
  name: '中医四诊信息',
  config: {
    sections: [
      {
        id: 'inspection',
        title: '望诊',
        fields: [
          {
            id: 'spirit',
            key: 'spirit',
            label: '望神',
            type: 'radio',
            props: { options: ['得神', '少神', '失神', '假神'] },
            storageKey: 'tcm_spirit',
          },
          {
            id: 'face_color',
            key: 'face_color',
            label: '望面色',
            type: 'radio',
            props: { options: ['红黄隐隐、明润含蓄', '色青', '色赤', '色黄', '色白', '色黑', '两颧潮红', '颧红如妆'] },
            storageKey: 'tcm_face_color',
          },
          {
            id: 'body_shape',
            key: 'body_shape',
            label: '望形态',
            type: 'input',
            props: { placeholder: '强弱胖瘦、肢体、体型' },
            storageKey: 'tcm_body_shape',
          },
          {
            id: 'tongue_body',
            key: 'tongue_body',
            label: '舌质',
            type: 'radio',
            props: { options: ['淡红(正常)', '红', '淡白', '绛舌', '淡紫', '绛紫', '红绛', '青紫'] },
            storageKey: 'tongue_body',
          },
          {
            id: 'tongue_shape',
            key: 'tongue_shape',
            label: '舌形',
            type: 'checkbox',
            props: { options: ['胖大', '肿胀', '瘦薄', '点刺', '裂纹', '光滑', '齿痕'] },
            storageKey: 'tcm_tongue_shape',
          },
          {
            id: 'tongue_coating',
            key: 'tongue_coating',
            label: '苔色',
            type: 'radio',
            props: { options: ['白', '黄', '灰', '黑', '绿'] },
            storageKey: 'tongue_coating',
          },
          {
            id: 'coating_quality',
            key: 'coating_quality',
            label: '苔质',
            type: 'checkbox',
            props: { options: ['厚', '薄', '剥落', '无根', '润泽', '滑利', '干燥', '燥裂', '腐苔', '腻苔'] },
            storageKey: 'tcm_coating_quality',
          },
        ],
      },
      {
        id: 'auscultation',
        title: '闻诊',
        fields: [
          {
            id: 'voice',
            key: 'voice',
            label: '听声音',
            type: 'checkbox',
            props: { options: ['音哑/失音', '声亢有力', '声音重浊', '语声低微', '呻吟不止', '沉默寡言', '烦躁多言', '咳嗽', '呼吸如常', '气喘', '喉间痰鸣'] },
            storageKey: 'tcm_voice',
          },
          {
            id: 'smell',
            key: 'smell',
            label: '嗅气味',
            type: 'checkbox',
            props: { options: ['口气', '汗气', '鼻臭', '身臭', '病室气味'] },
            storageKey: 'tcm_smell',
          },
        ],
      },
      {
        id: 'inquiry',
        title: '问诊',
        fields: [
          {
            id: 'cold_heat',
            key: 'cold_heat',
            label: '寒热',
            type: 'radio',
            props: { options: ['无异常', '恶寒发热', '但热不寒', '但寒不热', '寒热往来', '恶寒重发热轻', '发热重恶寒轻', '壮热', '潮热', '微热'] },
            storageKey: 'tcm_cold_heat',
          },
          {
            id: 'sweating',
            key: 'sweating',
            label: '出汗',
            type: 'checkbox',
            props: { options: ['自汗', '盗汗', '大汗', '战汗', '头汗', '半身汗', '手足心汗'] },
            storageKey: 'tcm_sweating',
          },
          {
            id: 'head_body',
            key: 'head_body',
            label: '头身',
            type: 'input',
            props: { placeholder: '头痛部位、头晕、身痛、身重、四肢痛、腰痛等' },
            storageKey: 'tcm_head_body',
          },
          {
            id: 'chest_abdomen',
            key: 'chest_abdomen',
            label: '胸胁脘腹',
            type: 'input',
            props: { placeholder: '疼痛部位、性质、伴随症状' },
            storageKey: 'tcm_chest_abdomen',
          },
          {
            id: 'ears_eyes',
            key: 'ears_eyes',
            label: '耳目',
            type: 'checkbox',
            props: { options: ['耳鸣', '耳聋', '重听', '目痛', '目眩', '目昏', '雀目'] },
            storageKey: 'tcm_ears_eyes',
          },
          {
            id: 'appetite',
            key: 'appetite',
            label: '饮食与口味',
            type: 'radio',
            props: { options: ['胃纳可', '纳呆', '多食易饥', '饥不欲食', '口不渴', '口渴多饮', '渴不多饮', '口淡乏味', '口甜粘腻', '口中泛酸', '口苦', '口咸'] },
            storageKey: 'tcm_appetite',
          },
          {
            id: 'sleep',
            key: 'sleep',
            label: '睡眠',
            type: 'radio',
            props: { options: ['睡眠安', '失眠', '不易入睡', '睡后易醒', '时时惊醒', '夜卧不安', '嗜睡'] },
            storageKey: 'tcm_sleep',
          },
          {
            id: 'stool',
            key: 'stool',
            label: '大便',
            type: 'radio',
            props: { options: ['大便调', '便秘', '泄泻', '完谷不化', '溏结不调', '肛门灼热', '排便不爽', '里急后重'] },
            storageKey: 'tcm_stool',
          },
          {
            id: 'urination',
            key: 'urination',
            label: '小便',
            type: 'radio',
            props: { options: ['小便可', '尿量增多', '尿量减少', '小便频数', '癃闭', '涩痛', '失禁', '遗尿'] },
            storageKey: 'tcm_urination',
          },
          {
            id: 'gynecology',
            key: 'gynecology',
            label: '妇女(经/带/胎/产)',
            type: 'input',
            props: { placeholder: '如为女性，请填写月经、带下、胎孕、产育情况' },
            storageKey: 'tcm_gynecology',
          },
        ],
      },
      {
        id: 'palpation',
        title: '切诊',
        fields: [
          {
            id: 'pulse',
            key: 'pulse',
            label: '脉诊',
            type: 'checkbox',
            props: { options: ['浮', '沉', '迟', '数', '洪', '微', '细', '散', '虚', '实', '滑', '涩', '长', '短', '弦', '芤', '紧', '缓', '革', '劳', '弱', '濡', '伏', '动', '促', '结', '代', '疾脉'] },
            storageKey: 'pulse',
          },
          {
            id: 'palpation',
            key: 'palpation',
            label: '按诊',
            type: 'input',
            props: { placeholder: '肌肤、手足、胸腹、俞穴' },
            storageKey: 'tcm_palpation',
          },
          {
            id: 'other_signs',
            key: 'other_signs',
            label: '其他',
            type: 'input',
            props: { placeholder: '其他中医体征描述' },
            storageKey: 'other_signs',
          },
        ],
      },
    ],
  },
};
